[package]
name = "proto"
version = "0.0.1"
authors = [ "Hyunsik Choi <hyunsik.choi at gmail dot com>" ]

[lib]
name = "proto"
path = "./lib.rs"

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"