[package]
name = "client"
version = "0.0.1"
authors = [ "Hyunsik Choi <hyunsik.choi at gmail dot com>" ]

[lib]
name = "client"
path = "./lib.rs"

[dependencies]
url = "*"

[dependencies.common]
path = "../common"